#For customer to configure RSC, internal keep this only default
#when remove all RSC, please also remove this line
PRODUCT_MSSI_CUSTOMER_RSC_NAMES := default

#For internal RSC configuration
PRODUCT_MSSI_MTK_RSC_NAMES := default
PRODUCT_MSSI_MTK_RSC_NAMES += op01
PRODUCT_MSSI_MTK_RSC_NAMES += op01_lwtg
PRODUCT_MSSI_MTK_RSC_NAMES += cmcc_om
PRODUCT_MSSI_MTK_RSC_NAMES += op09
PRODUCT_MSSI_MTK_RSC_NAMES += op02_lwctg
PRODUCT_MSSI_MTK_RSC_NAMES += op02_lwg
PRODUCT_MSSI_MTK_RSC_NAMES += op02_lwtg
#for internal MAPI test
PRODUCT_MSSI_MTK_RSC_NAMES += mapi
PRODUCT_MSSI_MTK_RSC_NAMES += nfc
PRODUCT_MSSI_MTK_RSC_NAMES += ss

#for rat mode
PRODUCT_MSSI_MTK_RSC_NAMES += C2k3m
PRODUCT_MSSI_MTK_RSC_NAMES += Fdd3m
PRODUCT_MSSI_MTK_RSC_NAMES += Tdd3m
PRODUCT_MSSI_MTK_RSC_NAMES += C2k4m
PRODUCT_MSSI_MTK_RSC_NAMES += Fdd4m
PRODUCT_MSSI_MTK_RSC_NAMES += Fdd4mNr
PRODUCT_MSSI_MTK_RSC_NAMES += C2k5m
PRODUCT_MSSI_MTK_RSC_NAMES += Fdd5m
PRODUCT_MSSI_MTK_RSC_NAMES += Fdd5mNr
PRODUCT_MSSI_MTK_RSC_NAMES += 6m
PRODUCT_MSSI_MTK_RSC_NAMES += 6mNr
#for internal GWSD test
PRODUCT_MSSI_MTK_RSC_NAMES += gwsd
