include device/mediatek/system/common/BoardConfig.mk
MALLOC_SVELTE := true

TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := cortex-a53
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi

TARGET_SYSTEM_PROP += device/mediatek/system/mssi_32_ago_ww/mssi_system.prop

ifdef SYS_TARGET_PROJECT
ifndef MTK_TARGET_PROJECT

BOARD_AVB_ENABLE := true
#BOARD_AVB_SYSTEM_ADD_HASHTREE_FOOTER_ARGS defined in common
#BOARD_AVB_SYSTEM_KEY_PATH defined in common
#BOARD_AVB_SYSTEM_ALGORITHM defined in common
#BOARD_AVB_SYSTEM_ROLLBACK_INDEX_LOCATION defined in common
#BOARD_AVB_PRODUCT_ADD_HASHTREE_FOOTER_ARGS defined in common
#BOARD_AVB_PRODUCT_SERVICES_ADD_HASHTREE_FOOTER_ARGS defined in common
#BOARD_BUILD_SYSTEM_ROOT_IMAGE defined in common
#AB_OTA_UPDATER defined in common

TARGET_NO_BOOTLOADER := true
BOARD_INCLUDE_RECOVERY_DTBO := true

BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_CACHEIMAGE_PARTITION_SIZE := 452984832

BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PREBUILT_VENDORIMAGE := $(TARGET_DEVICE_DIR)/vendor.img
TARGET_COPY_OUT_VENDOR := vendor

BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4

BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_PRODUCT := product

ifeq ($(strip $(TARGET_COPY_OUT_ODM)),yes)
TARGET_COPY_OUT_ODM := odm
else ifeq ($(strip $(TARGET_COPY_OUT_ODM)),no)
TARGET_COPY_OUT_ODM := vendor/odm
endif

ifeq ($(PRODUCT_USE_DYNAMIC_PARTITIONS), true)
BOARD_AVB_VBMETA_SYSTEM := system product
BOARD_SUPER_PARTITION_GROUPS := main
BOARD_MAIN_PARTITION_LIST := system product
BOARD_MAIN_SIZE := 3221225472
else
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3221225472
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 452984832
endif

#W1923 Android Q new feature UDC
BOARD_ROOT_EXTRA_FOLDERS += metadata
BOARD_USES_METADATA_PARTITION := true

-include device/mediatek/build/core/soong_config.mk

endif#MTK_TARGET_PROJECT
endif#SYS_TARGET_PROJECT
