#For customer to configure RSC, internal keep this only default
#when remove all RSC, please also remove this line
PRODUCT_MSSI_CUSTOMER_RSC_NAMES := default

#For internal RSC configuration
PRODUCT_MSSI_MTK_RSC_NAMES := default
PRODUCT_MSSI_MTK_RSC_NAMES += ss
PRODUCT_MSSI_MTK_RSC_NAMES += dsds
PRODUCT_MSSI_MTK_RSC_NAMES += C2k3m
PRODUCT_MSSI_MTK_RSC_NAMES += Fdd3m
PRODUCT_MSSI_MTK_RSC_NAMES += Tdd3m
PRODUCT_MSSI_MTK_RSC_NAMES += C2k4m
PRODUCT_MSSI_MTK_RSC_NAMES += Fdd4m
PRODUCT_MSSI_MTK_RSC_NAMES += Fdd4mNr
PRODUCT_MSSI_MTK_RSC_NAMES += C2k5m
PRODUCT_MSSI_MTK_RSC_NAMES += Fdd5m
PRODUCT_MSSI_MTK_RSC_NAMES += Fdd5mNr
PRODUCT_MSSI_MTK_RSC_NAMES += 6m
PRODUCT_MSSI_MTK_RSC_NAMES += 6mNr
