# Copyright (C) 2018 MediaTek Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

obj-y += audio_ipi_platform.o

ccflags-y += -I$(srctree)/drivers/misc/mediatek/hifidsp_audio_ipi/common/framework
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hifi_dsp/$(CONFIG_MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/hifi_dsp/common
